name: SonarQube Cloud Analysis

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    - cron: '0 3 * * 1'  # Weekly on Monday at 3 AM

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  sonarqube-analysis:
    name: SonarQube Cloud Scan
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Detect project type
        id: detect
        run: |
          if [ -f "pom.xml" ]; then
            echo "type=maven" >> $GITHUB_OUTPUT
            echo "language=java" >> $GITHUB_OUTPUT
          elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            echo "type=gradle" >> $GITHUB_OUTPUT
            echo "language=java" >> $GITHUB_OUTPUT
          elif [ -f "package.json" ]; then
            echo "type=npm" >> $GITHUB_OUTPUT
            echo "language=javascript" >> $GITHUB_OUTPUT
          elif [ -f "requirements.txt" ] || [ -f "setup.py" ] || [ -f "pyproject.toml" ]; then
            echo "type=python" >> $GITHUB_OUTPUT
            echo "language=python" >> $GITHUB_OUTPUT
          elif [ -f "*.csproj" ] || [ -f "*.sln" ]; then
            echo "type=dotnet" >> $GITHUB_OUTPUT
            echo "language=csharp" >> $GITHUB_OUTPUT
          else
            echo "type=unknown" >> $GITHUB_OUTPUT
            echo "language=unknown" >> $GITHUB_OUTPUT
          fi
      
      - name: Set up JDK 17 (for Java projects)
        if: steps.detect.outputs.language == 'java'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Set up Node.js (for JavaScript projects)
        if: steps.detect.outputs.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Set up Python (for Python projects)
        if: steps.detect.outputs.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Set up .NET (for C# projects)
        if: steps.detect.outputs.language == 'csharp'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Install dependencies and run tests (Maven)
        if: steps.detect.outputs.type == 'maven'
        run: |
          mvn clean compile test-compile
          mvn surefire:test
      
      - name: Install dependencies and run tests (Gradle)
        if: steps.detect.outputs.type == 'gradle'
        run: |
          ./gradlew clean build test
      
      - name: Install dependencies and run tests (NPM)
        if: steps.detect.outputs.type == 'npm'
        run: |
          npm ci
          npm run test --if-present
          npm run build --if-present
      
      - name: Install dependencies and run tests (Python)
        if: steps.detect.outputs.type == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e .; fi
          pytest --cov=. --cov-report=xml --cov-report=html
      
      - name: Install dependencies and run tests (.NET)
        if: steps.detect.outputs.type == 'dotnet'
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ github.repository_owner }}
            -Dsonar.projectKey=${{ github.repository }}
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=300
      
      - name: Comment PR with SonarQube results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Try to get SonarQube results from the scan
            // This is a simplified version - in production, you'd query the SonarQube API
            let comment = '## 🔍 SonarQube Cloud Analysis Results\n\n';
            comment += '✅ **SonarQube analysis completed successfully**\n\n';
            comment += '📊 **Quality Gate**: Check SonarCloud dashboard for detailed results\n\n';
            comment += '🔗 **Dashboard**: [View in SonarCloud](https://sonarcloud.io/dashboard?id=${{ github.repository }})\n\n';
            comment += '---\n';
            comment += '💡 **Tip**: Address any issues flagged in the Quality Gate before merging.';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/
            **/coverage.xml
            **/TestResults/
          retention-days: 30

  sonarqube-quality-gate:
    name: SonarQube Quality Gate Check
    runs-on: ubuntu-latest
    needs: sonarqube-analysis
    if: always()
    
    steps:
      - name: Check Quality Gate Status
        uses: actions/github-script@v7
        with:
          script: |
            console.log('SonarQube Cloud analysis completed');
            console.log('Quality Gate status will be available in SonarCloud dashboard');
            console.log('Review the Quality Gate results before merging PR');

      - name: Fail if Quality Gate failed
        if: failure()
        run: |
          echo "❌ SonarQube Quality Gate failed"
          echo "Please review the issues in SonarCloud dashboard and fix them before merging"
          exit 1